"""support structured extraction

Revision ID: 7af44def6f21
Revises: ed400f92bdfe
Create Date: 2026-08-14 16:11:27.220461
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7af44def6f21'
down_revision: str | None = 'ed400f92bdfe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alias_assertions', sa.Column('alias_kind', sa.String(length=32), nullable=False))
    op.add_column('expression_observations', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'expression_observations', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expression_observations', type_='unique')
    op.drop_column('expression_observations', 'fingerprint')
    op.drop_column('alias_assertions', 'alias_kind')
    # ### end Alembic commands ###
