"""create revised core schema

Revision ID: ed400f92bdfe
Revises: 
Create Date: 2026-08-14 14:37:35.610537
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ed400f92bdfe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('artifact_kind', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_artifacts_created_at'), 'artifacts', ['created_at'], unique=False)
    op.create_table('novels',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_created_at'), 'novels', ['created_at'], unique=False)
    op.create_index(op.f('ix_novels_status'), 'novels', ['status'], unique=False)
    op.create_table('characters',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'canonical_name')
    )
    op.create_index(op.f('ix_characters_created_at'), 'characters', ['created_at'], unique=False)
    op.create_index(op.f('ix_characters_novel_id'), 'characters', ['novel_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('run_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_pipeline_runs_created_at'), 'pipeline_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_novel_id'), 'pipeline_runs', ['novel_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False)
    op.create_table('source_documents',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('normalization_map_version', sa.String(length=64), nullable=True),
    sa.Column('normalization_map', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_source_documents_created_at'), 'source_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_documents_novel_id'), 'source_documents', ['novel_id'], unique=False)
    op.create_table('timelines',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_timeline_id', sa.Uuid(), nullable=True),
    sa.Column('branch_event_id', sa.Uuid(), nullable=True),
    sa.Column('canonicality', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timelines_branch_event_id'), 'timelines', ['branch_event_id'], unique=False)
    op.create_index(op.f('ix_timelines_novel_id'), 'timelines', ['novel_id'], unique=False)
    op.create_table('chapters',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('original_char_start', sa.Integer(), nullable=False),
    sa.Column('original_char_end', sa.Integer(), nullable=False),
    sa.Column('normalized_char_start', sa.Integer(), nullable=False),
    sa.Column('normalized_char_end', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('normalized_char_end > normalized_char_start', name='ck_chapters_normalized_span'),
    sa.CheckConstraint('ordinal >= 0', name='ck_chapters_ordinal_nonnegative'),
    sa.CheckConstraint('original_char_end > original_char_start', name='ck_chapters_original_span'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'ordinal')
    )
    op.create_table('character_appearance_states',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('temporal_scope', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('age_stage', sa.String(length=100), nullable=True),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('field_sources', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_appearance_states_created_at'), 'character_appearance_states', ['created_at'], unique=False)
    op.create_table('generated_images',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_profile', sa.String(length=100), nullable=False),
    sa.Column('workflow_version', sa.String(length=100), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_created_at'), 'generated_images', ['created_at'], unique=False)
    op.create_table('pipeline_steps',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_generation', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt >= 0', name='ck_pipeline_steps_attempt_nonnegative'),
    sa.CheckConstraint('lease_generation >= 0', name='ck_pipeline_steps_generation_nonnegative'),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'step_key')
    )
    op.create_index('ix_pipeline_steps_claim', 'pipeline_steps', ['status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_pipeline_steps_created_at'), 'pipeline_steps', ['created_at'], unique=False)
    op.create_table('run_events',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'sequence')
    )
    op.create_table('story_events',
    sa.Column('timeline_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('story_order', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_events_timeline_id'), 'story_events', ['timeline_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('pipeline_step_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('agent_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('budget', sa.JSON(), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('final_output_hash', sa.String(length=64), nullable=True),
    sa.Column('stop_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_table('character_render_profiles',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('identity_anchor', sa.JSON(), nullable=False),
    sa.Column('default_appearance_state_id', sa.Uuid(), nullable=True),
    sa.Column('appearance_state_ids', sa.JSON(), nullable=False),
    sa.Column('palette', sa.JSON(), nullable=False),
    sa.Column('field_sources', sa.JSON(), nullable=False),
    sa.Column('unresolved_conflicts', sa.JSON(), nullable=False),
    sa.Column('style_preset', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_appearance_state_id'], ['character_appearance_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'version')
    )
    op.create_index(op.f('ix_character_render_profiles_created_at'), 'character_render_profiles', ['created_at'], unique=False)
    op.create_table('external_operations',
    sa.Column('pipeline_step_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('operation_kind', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ),
    sa.ForeignKeyConstraint(['pipeline_step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'idempotency_key')
    )
    op.create_index(op.f('ix_external_operations_created_at'), 'external_operations', ['created_at'], unique=False)
    op.create_index(op.f('ix_external_operations_provider_request_id'), 'external_operations', ['provider_request_id'], unique=False)
    op.create_index(op.f('ix_external_operations_status'), 'external_operations', ['status'], unique=False)
    op.create_table('human_approvals',
    sa.Column('pipeline_step_id', sa.Uuid(), nullable=False),
    sa.Column('action_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('opposing_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('estimated_cost', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('modifications', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_token_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_hash'),
    sa.UniqueConstraint('recovery_token_hash')
    )
    op.create_index(op.f('ix_human_approvals_created_at'), 'human_approvals', ['created_at'], unique=False)
    op.create_index(op.f('ix_human_approvals_status'), 'human_approvals', ['status'], unique=False)
    op.create_table('model_calls',
    sa.Column('pipeline_step_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=255), nullable=True),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('pricing_snapshot', sa.JSON(), nullable=True),
    sa.Column('finish_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_step_id'], ['pipeline_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_calls_created_at'), 'model_calls', ['created_at'], unique=False)
    op.create_table('scenes',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('timeline_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('chapter_ordinal', sa.Integer(), nullable=False),
    sa.Column('narrative_order', sa.Integer(), nullable=False),
    sa.Column('point_of_view_character_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['point_of_view_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'narrative_order')
    )
    op.create_table('text_chunks',
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('original_char_start', sa.Integer(), nullable=False),
    sa.Column('original_char_end', sa.Integer(), nullable=False),
    sa.Column('normalized_char_start', sa.Integer(), nullable=False),
    sa.Column('normalized_char_end', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('normalized_char_end > normalized_char_start', name='ck_text_chunks_normalized_span'),
    sa.CheckConstraint('ordinal >= 0', name='ck_text_chunks_ordinal_nonnegative'),
    sa.CheckConstraint('original_char_end > original_char_start', name='ck_text_chunks_original_span'),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('novel_id', 'ordinal', 'content_hash')
    )
    op.create_index('ix_text_chunks_document_ordinal', 'text_chunks', ['source_document_id', 'ordinal'], unique=False)
    op.create_table('agent_evaluations',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('evaluation_set', sa.String(length=255), nullable=False),
    sa.Column('evaluator_version', sa.String(length=100), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_evaluations_created_at'), 'agent_evaluations', ['created_at'], unique=False)
    op.create_table('agent_turns',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('input_context_hash', sa.String(length=64), nullable=False),
    sa.Column('output_summary', sa.JSON(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'turn_number')
    )
    op.create_index(op.f('ix_agent_turns_created_at'), 'agent_turns', ['created_at'], unique=False)
    op.create_table('character_image_sets',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('render_profile_id', sa.Uuid(), nullable=False),
    sa.Column('render_profile_version', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('default_representative_image_id', sa.Uuid(), nullable=True),
    sa.Column('stage_image_ids', sa.JSON(), nullable=False),
    sa.Column('selection_policy_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_profile_id'], ['character_render_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'version')
    )
    op.create_index(op.f('ix_character_image_sets_created_at'), 'character_image_sets', ['created_at'], unique=False)
    op.create_index(op.f('ix_character_image_sets_default_representative_image_id'), 'character_image_sets', ['default_representative_image_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_run_id', sa.Uuid(), nullable=True),
    sa.Column('decision_kind', sa.String(length=100), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_records_created_at'), 'decision_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_decision_records_subject_id'), 'decision_records', ['subject_id'], unique=False)
    op.create_table('expression_observations',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('outward_emotion', sa.String(length=32), nullable=False),
    sa.Column('expression_text', sa.String(length=500), nullable=True),
    sa.Column('visible_cues', sa.JSON(), nullable=False),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('arousal', sa.Float(), nullable=True),
    sa.Column('is_masked', sa.Boolean(), nullable=True),
    sa.Column('internal_emotion', sa.String(length=255), nullable=True),
    sa.Column('target_character_id', sa.Uuid(), nullable=True),
    sa.Column('cause_event_id', sa.Uuid(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('temporal_scope', sa.JSON(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_end > char_start', name='ck_expression_observations_span'),
    sa.CheckConstraint('char_start >= 0', name='ck_expression_observations_start'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_expression_observations_confidence'),
    sa.ForeignKeyConstraint(['cause_event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['text_chunks.id'], ),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expression_observations_created_at'), 'expression_observations', ['created_at'], unique=False)
    op.create_table('feature_observations',
    sa.Column('character_id', sa.Uuid(), nullable=False),
    sa.Column('field_path', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('chapter_ordinal', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('temporal_scope', sa.JSON(), nullable=True),
    sa.Column('epistemic_status', sa.String(length=32), nullable=False),
    sa.Column('grounding_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extraction_run_id', sa.Uuid(), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(char_start IS NULL AND char_end IS NULL) OR (char_start >= 0 AND char_end > char_start)', name='ck_feature_observations_span'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_feature_observations_confidence'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['story_events.id'], ),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['text_chunks.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['feature_observations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index('ix_feature_observations_character_field', 'feature_observations', ['character_id', 'field_path'], unique=False)
    op.create_index(op.f('ix_feature_observations_created_at'), 'feature_observations', ['created_at'], unique=False)
    op.create_table('mention_spans',
    sa.Column('source_document_version', sa.String(length=64), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('mention_text', sa.Text(), nullable=False),
    sa.Column('mention_kind', sa.String(length=32), nullable=False),
    sa.Column('candidate_character_ids', sa.JSON(), nullable=False),
    sa.Column('resolved_character_id', sa.Uuid(), nullable=True),
    sa.Column('grounding_status', sa.String(length=32), nullable=False),
    sa.Column('normalization_map_version', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('char_end > char_start', name='ck_mention_spans_valid_span'),
    sa.CheckConstraint('char_start >= 0', name='ck_mention_spans_start_nonnegative'),
    sa.ForeignKeyConstraint(['resolved_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['text_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mention_spans_created_at'), 'mention_spans', ['created_at'], unique=False)
    op.create_table('tool_calls',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('tool_version', sa.String(length=100), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('side_effect', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.create_index(op.f('ix_tool_calls_created_at'), 'tool_calls', ['created_at'], unique=False)
    op.create_table('alias_assertions',
    sa.Column('alias_text', sa.String(length=255), nullable=False),
    sa.Column('normalized_alias', sa.String(length=255), nullable=False),
    sa.Column('mention_span_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_character_id', sa.Uuid(), nullable=True),
    sa.Column('speaker_id', sa.Uuid(), nullable=True),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('timeline_id', sa.Uuid(), nullable=True),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('opposing_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mention_span_id'], ['mention_spans.id'], ),
    sa.ForeignKeyConstraint(['proposed_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alias_assertions_created_at'), 'alias_assertions', ['created_at'], unique=False)
    op.create_index('ix_alias_assertions_normalized', 'alias_assertions', ['normalized_alias'], unique=False)
    op.create_table('character_stage_images',
    sa.Column('image_set_id', sa.Uuid(), nullable=False),
    sa.Column('appearance_state_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('stage_label', sa.String(length=255), nullable=False),
    sa.Column('representative_event_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_image_ids', sa.JSON(), nullable=False),
    sa.Column('baseline_image_id', sa.Uuid(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('selection_reason_codes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appearance_state_id'], ['character_appearance_states.id'], ),
    sa.ForeignKeyConstraint(['baseline_image_id'], ['generated_images.id'], ),
    sa.ForeignKeyConstraint(['image_set_id'], ['character_image_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['representative_event_id'], ['story_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_set_id', 'appearance_state_id')
    )
    op.create_index(op.f('ix_character_stage_images_created_at'), 'character_stage_images', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_stage_images_created_at'), table_name='character_stage_images')
    op.drop_table('character_stage_images')
    op.drop_index('ix_alias_assertions_normalized', table_name='alias_assertions')
    op.drop_index(op.f('ix_alias_assertions_created_at'), table_name='alias_assertions')
    op.drop_table('alias_assertions')
    op.drop_index(op.f('ix_tool_calls_created_at'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_mention_spans_created_at'), table_name='mention_spans')
    op.drop_table('mention_spans')
    op.drop_index(op.f('ix_feature_observations_created_at'), table_name='feature_observations')
    op.drop_index('ix_feature_observations_character_field', table_name='feature_observations')
    op.drop_table('feature_observations')
    op.drop_index(op.f('ix_expression_observations_created_at'), table_name='expression_observations')
    op.drop_table('expression_observations')
    op.drop_index(op.f('ix_decision_records_subject_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_created_at'), table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_character_image_sets_default_representative_image_id'), table_name='character_image_sets')
    op.drop_index(op.f('ix_character_image_sets_created_at'), table_name='character_image_sets')
    op.drop_table('character_image_sets')
    op.drop_index(op.f('ix_agent_turns_created_at'), table_name='agent_turns')
    op.drop_table('agent_turns')
    op.drop_index(op.f('ix_agent_evaluations_created_at'), table_name='agent_evaluations')
    op.drop_table('agent_evaluations')
    op.drop_index('ix_text_chunks_document_ordinal', table_name='text_chunks')
    op.drop_table('text_chunks')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_model_calls_created_at'), table_name='model_calls')
    op.drop_table('model_calls')
    op.drop_index(op.f('ix_human_approvals_status'), table_name='human_approvals')
    op.drop_index(op.f('ix_human_approvals_created_at'), table_name='human_approvals')
    op.drop_table('human_approvals')
    op.drop_index(op.f('ix_external_operations_status'), table_name='external_operations')
    op.drop_index(op.f('ix_external_operations_provider_request_id'), table_name='external_operations')
    op.drop_index(op.f('ix_external_operations_created_at'), table_name='external_operations')
    op.drop_table('external_operations')
    op.drop_index(op.f('ix_character_render_profiles_created_at'), table_name='character_render_profiles')
    op.drop_table('character_render_profiles')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_story_events_timeline_id'), table_name='story_events')
    op.drop_table('story_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_pipeline_steps_created_at'), table_name='pipeline_steps')
    op.drop_index('ix_pipeline_steps_claim', table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_index(op.f('ix_generated_images_created_at'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_character_appearance_states_created_at'), table_name='character_appearance_states')
    op.drop_table('character_appearance_states')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_timelines_novel_id'), table_name='timelines')
    op.drop_index(op.f('ix_timelines_branch_event_id'), table_name='timelines')
    op.drop_table('timelines')
    op.drop_index(op.f('ix_source_documents_novel_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_created_at'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_pipeline_runs_status'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_novel_id'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_created_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_characters_novel_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_created_at'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_novels_status'), table_name='novels')
    op.drop_index(op.f('ix_novels_created_at'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_artifacts_created_at'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
